### ISSUE TITLE
Parametro sourceApp per ritorno da CieID

### ISSUE THREAD

**Issue by evabafaro** [italia/cieid-ios-sdk#5]
Salve,
provando ad integrare l'SDK per effettuare l'autenticazione tramite CIE riscontro il seguente comportamento: l'app CieID viene aperta, si riesce ad effettuare l'autenticazione tramite CIE, ma dopo che appare l'avviso "Riapertura dell'app" si resta bloccati su CieID, senza tornare all'app chiamante.  
L'URL Scheme è configurato correttamente e lo stesso comportamento avviene su più iPhone che rispettano i requisiti tecnici.

Nel file `Extensions/QueryString.swift` il parametro sourceApp viene così inserito nell'URL: 
```swift
return self.appendingPathComponent("&\(SOURCE_APP)=\(urlSchemeString)",` isDirectory: false)
```
Generando ad esempio la seguente richiesta:  `CIEID://https://ios.idserver.servizicie.interno.gov.it/idp/login/app/&sourceApp=xxx?opId=...`,  
mentre generando l'URL in modo da ottenere la seguente struttura, l'autenticazione va a buon fine e si ritorna all'app chiamante: `CIEID://https://ios.idserver.servizicie.interno.gov.it/idp/login/app?sourceApp=xxx&opId=...`

**Comment by levieu** [comment]
Per costruire correttamente l'URL si può sostituire 
`return self.appendingPathComponent("&\(SOURCE_APP)=\(urlSchemeString)", isDirectory: false)`
con
`return self.appending("sourceApp", value: "\(urlSchemeString)")`

dove appending equivale a 
`func appending(_ queryItem: String, value: String?) -> URL {

        guard var urlComponents = URLComponents(string: absoluteString) else { return absoluteURL }

        // Create array of existing query items
        var queryItems: [URLQueryItem] = urlComponents.queryItems ??  []

        // Create query item
        let queryItem = URLQueryItem(name: queryItem, value: value)

        // Append the new query item in the existing query items array
        queryItems.append(queryItem)

        // Append updated query items array in the url component object
        urlComponents.queryItems = queryItems

        // Returns the url from new url components
        return urlComponents.url!
    }`
